# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(blank=True),
        ),
    ]
