# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.CharField(max_length=20),
        ),
    ]
