# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0003_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateField(),
        ),
    ]
